Web/ViewModels/AdvogadoViewModel.cs
using Dominio;
using System;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels
{
    [Serializable]
    public class AdvogadoViewModel : EnderecoViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public SenioridadeEnum Senioridade { get; set; }

        public EnderecoViewModel Endereco { get; set; }
    }
}

Web/ViewModels/EnderecoViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels
{
    [Serializable]
    public class EnderecoViewModel
    {
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Logradouro { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(100, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Bairro { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Estado { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public string Cep { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Por favor, insira somente números.")] //Somente numero
        [StringLength(50, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 1)]
        public string Numero { get; set; }

        [StringLength(20, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres")]
        public string Complemento { get; set; }


        public int AdvogadoId { get; set; }
    }
}

Web/Controllers/AdvogadoController.cs
using Dominio;
using Repository.Implementacao;
using Repository.Interface;
using System;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using Web.ViewModels;


namespace Web.Controllers
{
   // [Authorize]
    public class AdvogadoController : Controller
    {
        private readonly IAdvogadoRepositorio _advogadoRepository;

        public AdvogadoController()
        {
            string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            _advogadoRepository = new AdvogadoRepositorio(connectionString);
        }

        public ActionResult Index()
        {
            var advogados = _advogadoRepository.ListarAdvogadoComEndereco();

            var advogadosViewModel = advogados.Select(advogado => new AdvogadoViewModel
            {
                Id = advogado.ID,
                Nome = advogado.Nome,
                Senioridade = advogado.Senioridade,
                Estado = advogado.endereco.Estado,
                Logradouro = advogado.endereco.Logradouro,
                Bairro = advogado.endereco.Bairro,
                Cep = advogado.endereco.Cep,
                Numero = advogado.endereco.Numero,
                Complemento = advogado.endereco.Complemento
            }).ToList(); 

            return View(advogadosViewModel);
        }

        public ActionResult Create()
        {
            ViewBag.Senioridades = Enum.GetValues(typeof(SenioridadeEnum)).Cast<SenioridadeEnum>();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AdvogadoViewModel advogadoViewModel)
        {
            if (advogadoViewModel.Id.Equals(null)) return RedirectToAction(nameof(Create));

            Advogado advogado = new Advogado
            {
                Nome = advogadoViewModel.Nome,
                Senioridade = (SenioridadeEnum)advogadoViewModel.Senioridade,
                endereco = new Endereco()
            };

            if (advogadoViewModel.Endereco != null)
            {
                advogado.endereco.Estado = advogadoViewModel.Endereco.Estado;
                advogado.endereco.Cep = advogadoViewModel.Endereco.Cep;
                advogado.endereco.Bairro = advogadoViewModel.Endereco.Bairro;
                advogado.endereco.Logradouro = advogadoViewModel.Endereco.Logradouro;
                advogado.endereco.Numero = advogadoViewModel.Endereco.Numero;
                advogado.endereco.Complemento = advogadoViewModel.Endereco.Complemento;
            }

            _advogadoRepository.Incluir(advogado);

            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Senioridades = Enum.GetValues(typeof(SenioridadeEnum)).Cast<SenioridadeEnum>();

            Advogado advogado = _advogadoRepository.BuscarPorId(id);

            if (advogado == null)
            {
                return RedirectToAction("Index");
            }

            AdvogadoViewModel advogadoViewModel = new AdvogadoViewModel
            {
                Nome = advogado.Nome,
                Senioridade = advogado.Senioridade,
                Estado = advogado.Estado,
                Logradouro = advogado.Logradouro,
                Cep = advogado.Cep,
                Numero = advogado.Numero,
                Complemento = advogado.Complemento,
                Bairro = advogado.Bairro,
            };

            return View(advogadoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AdvogadoViewModel advogadoViewModel)
        {
            if (!ModelState.IsValid) return RedirectToAction(nameof(Index));

            Advogado advogado = new Advogado
            {
                ID = advogadoViewModel.Id,
                Nome = advogadoViewModel.Nome,
                Senioridade = (SenioridadeEnum)advogadoViewModel.Senioridade,
                Estado = advogadoViewModel.Estado,
                Cep = advogadoViewModel.Cep,
                Bairro = advogadoViewModel.Bairro,
                Logradouro = advogadoViewModel.Logradouro,
                Numero = advogadoViewModel.Numero,
                Complemento = advogadoViewModel.Complemento,
            };

            _advogadoRepository.Atualizar(advogado);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var advogado = _advogadoRepository.BuscarPorId(id);
            if (advogado == null) return RedirectToAction("Index");

            AdvogadoViewModel advogadoViewModel = new AdvogadoViewModel
            {
                Nome = advogado.Nome,
                Senioridade = advogado.Senioridade,
                Estado = advogado.Estado,
                Logradouro = advogado.Logradouro,
                Cep = advogado.Cep,
                Numero = advogado.Numero,
                Complemento = advogado.Complemento,
                Bairro = advogado.Bairro,
            };

            return View(advogadoViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult ComfirmarExclusão(int id)
        {
            var advogadoviwmodel = _advogadoRepository.BuscarPorId(id);
            if (advogadoviwmodel == null) return RedirectToAction("Index");

            _advogadoRepository.Excluir(id);

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var advogado = _advogadoRepository.BuscarPorId(id);
            if (advogado == null) return RedirectToAction("Index");

            AdvogadoViewModel advogadoViewModel = new AdvogadoViewModel
            {
                Nome = advogado.Nome,
                Senioridade = advogado.Senioridade,
                Estado = advogado.Estado,
                Logradouro = advogado.Logradouro,
                Cep = advogado.Cep,
                Numero = advogado.Numero,
                Complemento = advogado.Complemento,
                Bairro = advogado.Bairro,
            };

            return View(advogadoViewModel);
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Web/Views/Advogado/Create.cshtml
@model Web.ViewModels.AdvogadoViewModel

@{
    ViewBag.Title = "Advogados | Novo";
}

<h2>@ViewBag.Title</h2>
<br /><br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Senioridade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Senioridade, new SelectList(ViewBag.Senioridades), "Selecione uma Senioridade", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Senioridade, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Endereco.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco.Cep, new { htmlAttributes = new { @class = "form-control", id = "cep" } })
                    @Html.ValidationMessageFor(model => model.Endereco.Cep, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Endereco.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco.Logradouro, new { htmlAttributes = new { @class = "form-control", id = "logradouro" } })
                    @Html.ValidationMessageFor(model => model.Endereco.Logradouro, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Endereco.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco.Bairro, new { htmlAttributes = new { @class = "form-control", id = "bairro" } })
                    @Html.ValidationMessageFor(model => model.Endereco.Bairro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Endereco.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco.Estado, new { htmlAttributes = new { @class = "form-control", id = "estado" } })
                    @Html.ValidationMessageFor(model => model.Endereco.Estado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Endereco.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco.Numero, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco.Numero, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Endereco.Complemento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco.Complemento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco.Complemento, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-0 col-md-10">
                <input type="submit" value="Criar" class="btn btn-success" />
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-warning" })
            </div>
        </div>
    </div>
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/scriptAdvogado/ScriptViaCEP.js"></script>

Web/Views/Advogado/Delete.cshtml
@model Web.ViewModels.AdvogadoViewModel

@{


    ViewBag.Title = "Advogado|Excluir";
}

<h2>@ViewBag.Title</h2>

<h3>Tem certeza de que deseja excluir este registro?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Senioridade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senioridade)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logradouro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complemento)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-warning" })
        </div>
    }
</div>

Web/Views/Advogado/Details.cshtml
@model Web.ViewModels.AdvogadoViewModel

@{
    ViewBag.Title = "Advogado|Detalhes";
}

<h2>@ViewBag.Title</h2>

<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Senioridade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senioridade)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logradouro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complemento)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-warning" })
</p>

Web/Views/Advogado/Edit.cshtml
@model Web.ViewModels.AdvogadoViewModel

@{
    ViewBag.Title = "Advogados | Atualizar";
}

<h2>@ViewBag.Title</h2>
<br /><br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Senioridade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Senioridade, new SelectList(ViewBag.Senioridades), "Selecione uma Senioridade", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Senioridade, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "form-control", id = "cep" } })
                    @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Logradouro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Logradouro, new { htmlAttributes = new { @class = "form-control", id = "logradouro" } })
                    @Html.ValidationMessageFor(model => model.Logradouro, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control", id = "bairro" } })
                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control", id = "estado" } })
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Complemento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Complemento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-0 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-warning" })
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-warning" })
    </div>*@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/scriptAdvogado/ScriptViaCEP.js"></script>

Web/Views/Advogado/Index.cshtml
@model IEnumerable<Web.ViewModels.AdvogadoViewModel>

@{
    ViewBag.Title = "Advogados | Início";
}
<br /><br />

<h2>@ViewBag.Title</h2>

<br /><br />
<p>
    @Html.ActionLink("Criar Novo", "Create", null, new { @class = "btn btn-primary btn-green" })
</p>
<br /><br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Senioridade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logradouro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bairro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cep)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Complemento)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelitem => item.Senioridade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Logradouro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bairro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cep)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Complemento)
            </td>


            <td>
                @Html.ActionLink("Atualizar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                
                @Html.ActionLink("Visualizar", "Details", new { id = item.Id }, new { @class = "btn btn-warning" })
                
                @Html.ActionLink("Excluir", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })

            </td>
        </tr>
    }

</table>

Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Advogado|Contato";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h2>Chalfin Goldberg Vainboim Advogados</h2>
    <p class="lead">
        Desde sua fundação, o CGV Advogados atua tanto na advocacia de grande volume quanto na advocacia estratégica.

        No segmento advocacia de grande volume, todo o trabalho administrativo é delegado a um time de paralegais,
        cabendo aos advogados dedicação exclusiva à análise e preparação dos casos. Dessa maneira, cadastro, acordos, encerramentos,
        entre outras "atividades meio", são realizadas pelo time de suporte.
        Tudo organizado através de uma esteira operacional, apoiada em workflow padronizado para todo o escritório..
    </p>
    <p><a target="_blank" href="https://www.cgvadvogados.com.br/" class="btn btn-primary btn-lg">Visitar site &raquo;</a></p>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | CGV</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CGV | Advogados", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cadastro", "Index", "Advogado")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -  Chalfin, Goldberg, Vainboim Advogados - Todos os direitos reservados.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>